# GitHub Pages Configuration
title: "Wilfierd - DevOps Engineer"
description: "Personal website and portfolio for Wilfierd, DevOps Engineer"
url: "https://wilfierd.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "Wilfierd"
twitter:
  username: wilfierd
social:
  name: Wilfierd
  links:
    - https://github.com/wilfierd
    - https://www.linkedin.com/in/wilfierddevop/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - _site
