name: Generate Snake Animation

on:
  push:
    branches:
      - raw-project # Trigger the action on push to this branch
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Specify the branch to check out
          ref: raw-project

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: wilfierd
          # The output path for the SVG file
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # The branch to publish to
          publish_branch: output 
          # Keep the history of the output branch clean
          force_orphan: true
